[project]
name = "deeprecurse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "fastmcp>=2.14.5",
    "modal>=1.3.3",
    "openai>=2.21.0",
    "rich>=14.3.2",
]
